import random
apologise_to_Sh=["Sh, my heart aches knowing I hurt you. You mean the world to me, and I’ll do anything to make it right.",
"I’m sorry, my love. Even the stars dim when you’re upset with me. Please forgive me.",
"Every moment without your smile feels like a lifetime. I promise to be better—for you, for us.",
"I messed up, and I hate seeing you hurt because of me. Can we rewrite this moment together?",
"You’re my favorite person, and I never want to be the reason for your tears. I’m truly sorry.",
"Okay, I admit it—I was a total goofball. Can I bribe you with hugs and chocolate to forgive me?",
"I’m sorry! If apologies were WiFi signals, you’d have full bars from me right now.",
"I take full responsibility… and also blame my lack of coffee (just kidding). Forgive me, Sh?",
"I promise I’ll be less of a disaster human if you give me one more chance. Deal?",
"Even my dog thinks I messed up. Please put me out of my misery and forgive me?",
"Sh, I regret my actions deeply. I never want to lose your trust—you mean too much to me.",
"I was wrong, and no excuse justifies it. All I can do is promise to learn from this.",
"Hurting you was never my intention. I hope you can find it in your heart to forgive me.",
"I owe you better, and I’ll prove it—not just with words, but with actions.",
"You deserve the world, and I hate that I let you down. I’ll spend every day making it up to you.",
"If love had an eraser, I’d wipe away every tear I caused. I’m sorry, Sh.",
"Your smile is my favorite melody—I hate that I silenced it, even briefly.",
"Like the moon misses the sun when it sets, I miss your warmth when we’re apart.",
"I’d rewrite every wrong word if it meant seeing your eyes light up again.",
"Our love is my greatest treasure, and I was careless with it. Forgive me?",
"I’m so sorry that even my pet goldfish is judging me right now.",
"If being sorry burned calories, I’d be in the best shape of my life by now.",
"I messed up—can we fast-forward to the make-up cuddles?",
"I take it back, undo it, Control+Z my mistake. Please reset to ‘happy Sh’ mode?",
"I promise to be less of an idiot. (But no guarantees on the ‘less clumsy’ part.)",
"I don’t deserve your forgiveness, but I’m begging for it anyway.",
"I failed you, and I’ll spend every day earning back your trust.",
"No excuses—just remorse. I’m so sorry, Sh.",
"I wish I could turn back time. All I can do is promise to do better.",
"If you give me another chance, I’ll prove I’m worth it."]
def apologise_to_Sh():
    return(random.choice(apologise_to_Sh))
