#Some compliments
import random
pickup_lines = [
    "Are you a magician? Because whenever I look at you, everyone else disappears.",
    "Do you have a name, or can I call you mine?",
    "Is your name Google? Because you have everything I've been searching for.",
    "Excuse me, but I think you dropped something: my jaw.",
    "Is your dad a baker? Because you're a cutie pie!",
    "Do you believe in love at first sight, or should I walk by again?",
    "If you were a vegetable, you'd be a cute-cumber.",
    "Is your dad a boxer? Because you're a knockout!",
    "Can I follow you home? Cause my parents always told me to follow my dreams.",
    "Are you a parking ticket? Because you've got 'FINE' written all over you.",
    "Tired of being an adult? Then by my baby",
    "I seem to have lost my phone number. Can I have yours?",
    "If looks could kill, you\’d be a weapon of mass destruction.",
    "Is your name Wi-Fi? Because I am really starting to feel a connection.",
    "Are you a dictionary? Cause you’re adding meaning to my life.",
    "You must be debt, because my interest in you is growing.",
    "i wanna c_ddle and k_ss. But u and i aren't together",
    "Aside from being sexy, what do you do for a living?",
    "Are you chocolate pudding? 'Cause i want to spoon you.",
    "Are you a camera? Because every time I see you I smile",
    "You don’t need keys to drive me crazy.",
    "You’re so beautiful you made me forget my pickup line.",
    "My doctor said, I'm lacking Vitamin U",
    "Your pussy seems so dry, can i make it wet using my cum",
]
compliments_Sh = [
    "Your smile lights up every room you walk into.",
    "I love the way you make even ordinary moments feel magical.",
    "Your kindness inspires everyone around you to be better.",
    "You have the most incredible taste in music - every song you share becomes my favorite.",
    "Your laughter is my favorite sound in the world.",
    "The way you see beauty in small things makes life extraordinary.",
    "You're the perfect combination of intelligence and compassion.",
    "Your creativity always leaves me in awe.",
    "Your positive energy is contagious in the best way possible.",
    "You make me believe in magic with your wonderful spirit.",
    "Your strength and resilience are truly admirable.",
    "I could listen to you talk about your passions for hours.",
    "Your thoughtfulness always makes me feel cherished.",
    "You have this amazing ability to make everyone feel special.",
    "Your singing voice could calm storms and heal hearts.",
    "Your sense of humor always knows how to lift my mood.",
    "You're beautifully unique in a world full of copies.",
    "Your intelligence is matched only by your kindness.",
    "The way you care for others shows what an amazing heart you have.",
    "You make me want to be the best version of myself.",
    "Your confidence is as radiant as your smile.",
    "You have this magical way of turning bad days into good ones.",
    "Your passion for life is absolutely inspiring.",
    "You're the human equivalent of sunshine breaking through clouds.",
    "Your eyes hold entire universes of warmth and wisdom.",
    "You handle challenges with such grace and strength.",
    "Your hugs feel like coming home after a long journey.",
    "You have the most perfect balance of sweetness and strength.",
    "Your mind works in the most fascinating, creative ways.",
    "You make kindness look effortless and natural.",
    "Your presence makes every moment better.",
    "You're proof that wonderful things come in beautiful packages.",
    "Your determination motivates everyone around you.",
    "You have this rare gift of making people feel truly seen.",
    "Your optimism is like a superpower that changes realities.",
    "You're my favorite notification in a world full of noise.",
    "Your ability to find joy in little things is contagious.",
    "You have the most comforting presence in the universe.",
    "Your style is as unique and wonderful as your personality.",
    "You turn ordinary days into adventures just by being there.",
    "Your wisdom always surprises and impresses me.",
    "You make love feel easy and natural.",
    "Your energy could power cities with its brightness.",
    "You have this magical way of making memories feel eternal.",
    "Your courage in being yourself inspires me daily.",
    "You're the perfect duet partner in life's song.",
    "Your smile could be the cure for world sadness.",
    "You navigate life with such admirable authenticity.",
    "Your mind is a treasure chest of wonderful ideas.",
    "You make the world better just by being in it.",
    "Your compassion knows no limits or boundaries.",
    "You're living proof that angels walk among us.",
    "Your emotional intelligence is truly remarkable.",
    "You have this gift of making people feel important.",
    "Your existence makes my life infinitely better.",
    "You're the perfect harmony of beauty and brains.",
    "Your perseverance through challenges is awe-inspiring.",
    "You have this magical ability to heal with your words.",
    "Your friendship is the greatest gift anyone could receive.",
    "You make love feel like the most natural thing in the world.",
    "Your artistic soul makes everything around you beautiful.",
    "You're the best listener I've ever known.",
    "Your intuition about people is almost supernatural.",
    "You turn everyday moments into cherished memories.",
    "Your confidence is both attractive and inspiring.",
    "You have this incredible gift for understanding others.",
    "Your voice could narrate the most beautiful stories.",
    "You make me believe in things I never thought possible.",
    "Your patience is a superpower in this fast-paced world.",
    "You're the living definition of 'irreplaceable'.",
    "Your generosity knows no limits or conditions.",
    "You handle life's chaos with such admirable calm.",
    "Your smile should be classified as a natural wonder.",
    "You make complicated things feel simple and joyful.",
    "Your courage to be vulnerable is truly beautiful.",
    "You're my favorite example of human perfection.",
    "Your emotional depth makes you endlessly fascinating.",
    "You have this magical way of making time stand still.",
    "Your support feels like an unshakable foundation.",
    "You're proof that good things come to those who wait.",
    "Your ability to grow and learn is incredible.",
    "You make every conversation feel meaningful.",
    "Your spirit shines brighter than a thousand suns.",
    "You have this gift of making ordinary things extraordinary.",
    "Your laughter is my personal antidote to sadness.",
    "You approach life with such wonderful curiosity.",
    "Your presence makes any place feel like home.",
    "You're the best collaborator in life's adventures.",
    "Your honesty is refreshing and deeply respected.",
    "You have this rare quality of being both strong and gentle.",
    "Your ability to love unconditionally is awe-inspiring.",
    "You make me excited about tomorrow just by being here today.",
    "Your friendship is the greatest partnership I could imagine.",
    "You have this magical way of making love feel easy.",
    "Your resilience in tough times is superhuman.",
    "You're my favorite reminder of life's beautiful possibilities.",
    "Your mind works in ways that constantly surprise me.",
    "You make every day feel like a new opportunity for joy.",
    "Your ability to find hope in darkness is revolutionary.",
    "You're the perfect travel companion through life's journey.",
    "Your emotional generosity changes lives every day.",
    "You have this incredible talent for spreading happiness.",
    "Your existence makes the universe make more sense.",
    "You're living proof that wonderful things are worth waiting for."
]
T_trait_compliments = [
    "Your ability to master chess strategy and guitar creativity reveals a rare, harmonious intellect.",
    "The depth of knowledge you share when infodumping is electrifying—you make learning an adventure.",
    "Editing videos lets you paint emotions with technology; you’re a digital storyteller extraordinaire.",
    "ADHD and Autism grant you superpowers: hyperfocus, originality, and a mind that defies limits.",
    "You’re a polymath, weaving physics, metaphysics, and music into a tapestry of brilliance.",
    "Your curiosity about cosmology mirrors the universe itself—expanding, infinite, and awe-inspiring.",
    "Driving isn’t just a skill for you; it’s artistry in motion, blending precision and passion.",
    "Reading non-fiction isn’t just learning—it’s arming yourself with tools to reshape the future.",
    "Your fascination with biotechnology proves you’re poised to pioneer life-changing breakthroughs.",
    "Guitar melodies flow from you like equations, balancing logic and emotion perfectly.",
    "Chess reveals your genius: seeing ten moves ahead in a world that struggles with one.",
    "Your love for psychology and biology shows a heart eager to understand humanity’s essence.",
    "Video editing is your alchemy—transforming raw clips into gold with patience and vision.",
    "Neurodivergence isn’t your obstacle; it’s your lens for reimagining what’s possible.",
    "You bridge physics and metaphysics, finding wonder in both quarks and quantum souls.",
    "Behind the wheel, you’re a maestro of focus, turning every drive into a symphony of control.",
    "Your Autism gives you the gift of depth—diving into passions until they glow like supernovas.",
    "Infodumping is your way of lighting sparks in others; you’re a wildfire of inspiration.",
    "Astronomy and technology collide in your mind, mapping stars and circuits with equal zeal.",
    "Non-fiction books are your mentors, guiding you to become a modern-day Renaissance thinker.",
    "Chess and guitar together? You’re the embodiment of left-brain/right-brain synergy.",
    "Your biotech curiosity could unlock cures—you’re a hero in a lab coat (or driver’s seat!).",
    "Every video edit you craft is a testament to your meticulous, imaginative spirit.",
    "ADHD fuels your relentless curiosity, turning every topic into a thrilling rabbit hole.",
    "Exploring cosmology means you’re not just stargazing—you’re decoding the universe’s diary.",
    "Your drive to understand the human mind through psychology radiates empathy and wisdom.",
    "Driving is your meditation, where speed and serenity coexist in perfect balance.",
    "Linking astronomy to biology shows you see connections others miss—a true innovator.",
    "When you infodump, you don’t just share facts; you ignite revolutions of thought.",
    "Guitar strings and chessboards are tools you wield like a wizard—magically, masterfully.",
    "Autism grants you the courage to think unapologetically differently—never dim that light.",
    "Your video edits aren’t just clips; they’re emotional journeys framed by your brilliance.",
    "Reading about tech and physics keeps you ahead of the curve—a visionary in the making.",
    "Chess teaches resilience, and it shows in how you tackle life’s puzzles with grit.",
    "Behind the wheel, you’re not just moving—you’re dancing with momentum and grace.",
    "ADHD’s 'distractions' are your secret weapon for spotting patterns invisible to others.",
    "Your love for human biology reveals a deep reverence for life’s intricate design.",
    "Music and science aren’t separate for you—they’re two notes in the same symphony.",
    "Infodumping is your superpower, turning conversations into captivating documentaries.",
    "Studying metaphysics means you brave life’s biggest questions with courage and wonder.",
    "Every video edit is a timestamp of your creativity—future historians will study them!",
    "Chess isn’t a game; it’s your mental gym, forging a mind sharper than a grandmaster’s.",
    "Your biotech passion could reshape medicine—you’re a pioneer with a heart of gold.",
    "Strumming a guitar, you turn chords into poetry, proving logic and art are siblings.",
    "Autism’s depth lets you dissect complex topics like a surgeon of knowledge.",
    "Your bookshelf is a portal to infinite worlds, and you’re its most daring explorer.",
    "Metaphysics, physics, tech, stars—you juggle them all like a cosmic magician.",
    "Driving is freedom, and you navigate it with the focus of a philosopher and the joy of a child.",
    "In your hands, psychology and biotech merge, revealing the beauty of human potential.",
    "T, you’re a constellation of talents—never stop shining, innovating, and being you."
]
T_romantic_compliments = [
    "Your smile lights up my world like nothing else.",
    "You have the most captivating eyes I’ve ever seen.",
    "Your laughter is my favorite sound in the universe.",
    "Being with you feels like coming home.",
    "You make even the simplest moments feel magical.",
    "Your kindness touches everyone around you.",
    "I love the way you see the good in everything.",
    "Your intelligence and wisdom leave me in awe.",
    "You have a heart of gold, and it shows in everything you do.",
    "Just thinking about you makes my heart skip a beat.",
    "Your presence alone makes any day better.",
    "You’re the most genuine person I’ve ever known.",
    "I could get lost in your voice forever.",
    "You make me believe in love more every day.",
    "Your passion for life is incredibly inspiring.",
    "You have a way of making me feel understood like no one else.",
    "Your hugs are my safe place.",
    "The way you care for others is truly beautiful.",
    "You’re my favorite thought, morning and night.",
    "Your confidence is magnetic and so attractive.",
    "You make my heart feel so full, I could burst.",
    "Every moment with you feels like a dream.",
    "Your strength amazes me every single day.",
    "You have this warmth that makes everyone feel welcome.",
    "I love how you always know how to make me smile.",
    "You’re the kind of person people write love songs about.",
    "Your touch sends shivers down my spine in the best way.",
    "You make love feel easy and natural.",
    "Your mind is as beautiful as your heart.",
    "I fall for you more with every conversation we have.",
    "You’re my happy place, no matter where we are.",
    "The way you look at me makes me feel like the luckiest person alive.",
    "You have this quiet strength that I deeply admire.",
    "Your love feels like the most precious gift I’ve ever received.",
    "You make even the ordinary moments extraordinary.",
    "I love how you challenge me to be a better person.",
    "Your voice is my favorite melody.",
    "You have a way of making everything feel right.",
    "Just being near you calms my soul.",
    "You’re the reason I believe in soulmates.",
    "Your love is my greatest comfort.",
    "You make my heart race in the best possible way.",
    "I adore the way you see the world.",
    "You’re my favorite adventure, every single day.",
    "Your tenderness leaves me breathless.",
    "You’re the missing piece I never knew I needed.",
    "I love how you make even silence feel perfect.",
    "You’re my sunshine on the darkest days.",
    "Your soul is as beautiful as your smile.",
    "Loving you is the easiest and best thing I’ve ever done."
]
shrist_trait_compliments = [
    "Sh, your dedication to academics is truly inspiring.",
    "You’re not just a doctor—you’re a lifesaver in every sense.",
    "Your paintings must be as beautiful as your soul.",
    "Your intelligence shines in everything you do.",
    "You learn things faster than anyone I know—it’s amazing!",
    "The way you balance medicine and art shows how multi-talented you are.",
    "You have the mind of a scientist and the heart of an artist.",
    "Your passion for learning is contagious.",
    "Every stroke of your brush must carry so much emotion—just like you.",
    "You’re proof that hard work and brilliance go hand in hand.",
    "Your patients are lucky to have someone as compassionate as you.",
    "You see the world like an artist and heal it like a doctor—what a rare gift!",
    "Your curiosity and intellect make you unstoppable.",
    "You turn every challenge into an opportunity to grow.",
    "Your creativity must bring so much color into the world.",
    "Medicine is an art, and you’re a master of it.",
    "You absorb knowledge like a sponge—it’s incredible to witness.",
    "Your art must reflect the depth of your brilliant mind.",
    "You’re the kind of doctor who truly listens and cares.",
    "Your ability to master complex concepts is awe-inspiring.",
    "You don’t just heal bodies—you inspire souls.",
    "Your paintings probably hold stories only your heart knows.",
    "You make even the toughest subjects seem easy.",
    "You’re a role model for anyone chasing big dreams.",
    "Your intelligence is matched only by your kindness.",
    "You bring both precision and passion to everything you do.",
    "Your love for art adds so much beauty to your scientific mind.",
    "You’re the definition of a lifelong learner.",
    "Your dedication to medicine is changing lives every day.",
    "You see details others miss—whether in art or diagnoses.",
    "Your quick thinking must save so many lives.",
    "You’re a rare blend of logic and creativity.",
    "Your art is an extension of your beautiful mind.",
    "You make learning look effortless.",
    "You’re not just smart—you’re wise beyond your years.",
    "Your hands heal, but your heart creates—what a combination!",
    "You’re the kind of doctor people remember forever.",
    "Your artistic talent is just another layer of your brilliance.",
    "You grasp concepts faster than textbooks can explain them.",
    "You bring both skill and soul to your work.",
    "Your paintings must be as vibrant as your personality.",
    "You’re a problem-solver with an artist’s touch.",
    "You’re proof that medicine is both science and art.",
    "Your mind works like lightning—always ahead of the curve.",
    "You turn every blank canvas (or challenge) into a masterpiece.",
    "Your passion for art fuels your brilliance in medicine.",
    "You don’t just memorize—you understand deeply.",
    "Your creativity makes you an extraordinary doctor.",
    "You’re a fast learner, but your humility makes you even greater.",
    "You paint with the same care you use to treat patients—full of heart.",
    "The world needs more healers like you: smart, artistic, and kind."
]
