import random, discord
token = 'Enter your token here'
#Enter user id of sid, T and SH below
userid={"Sid":1"Sh":2,"T":3}
serverid = 0 #Enter your server id here
def get_truth():
    return(random.choice(truth_questions))
def get_dare():
    return(random.choice(dares))
def rotate_bottle(interaction:discord.Interaction):
    players=["Sh", "T"]
    member=interaction.guild.fetch_member(userid["Sid"])
    permissions=interaction.channel.permissions_for(member)
    if(permissions.read_messages):
        players.append("Sid")
    return(random.choice(players))
compliments_Sh = [
    "Your smile lights up every room you walk into.",
    "I love the way you make even ordinary moments feel magical.",
    "Your kindness inspires everyone around you to be better.",
    "You have the most incredible taste in music - every song you share becomes my favorite.",
    "Your laughter is my favorite sound in the world.",
    "The way you see beauty in small things makes life extraordinary.",
    "You're the perfect combination of intelligence and compassion.",
    "Your creativity always leaves me in awe.",
    "Your positive energy is contagious in the best way possible.",
    "You make me believe in magic with your wonderful spirit.",
    "Your strength and resilience are truly admirable.",
    "I could listen to you talk about your passions for hours.",
    "Your thoughtfulness always makes me feel cherished.",
    "You have this amazing ability to make everyone feel special.",
    "Your singing voice could calm storms and heal hearts.",
    "Your sense of humor always knows how to lift my mood.",
    "You're beautifully unique in a world full of copies.",
    "Your intelligence is matched only by your kindness.",
    "The way you care for others shows what an amazing heart you have.",
    "You make me want to be the best version of myself.",
    "Your confidence is as radiant as your smile.",
    "You have this magical way of turning bad days into good ones.",
    "Your passion for life is absolutely inspiring.",
    "You're the human equivalent of sunshine breaking through clouds.",
    "Your eyes hold entire universes of warmth and wisdom.",
    "You handle challenges with such grace and strength.",
    "Your hugs feel like coming home after a long journey.",
    "You have the most perfect balance of sweetness and strength.",
    "Your mind works in the most fascinating, creative ways.",
    "You make kindness look effortless and natural.",
    "Your presence makes every moment better.",
    "You're proof that wonderful things come in beautiful packages.",
    "Your determination motivates everyone around you.",
    "You have this rare gift of making people feel truly seen.",
    "Your optimism is like a superpower that changes realities.",
    "You're my favorite notification in a world full of noise.",
    "Your ability to find joy in little things is contagious.",
    "You have the most comforting presence in the universe.",
    "Your style is as unique and wonderful as your personality.",
    "You turn ordinary days into adventures just by being there.",
    "Your wisdom always surprises and impresses me.",
    "You make love feel easy and natural.",
    "Your energy could power cities with its brightness.",
    "You have this magical way of making memories feel eternal.",
    "Your courage in being yourself inspires me daily.",
    "You're the perfect duet partner in life's song.",
    "Your smile could be the cure for world sadness.",
    "You navigate life with such admirable authenticity.",
    "Your mind is a treasure chest of wonderful ideas.",
    "You make the world better just by being in it.",
    "Your compassion knows no limits or boundaries.",
    "You're living proof that angels walk among us.",
    "Your emotional intelligence is truly remarkable.",
    "You have this gift of making people feel important.",
    "Your existence makes my life infinitely better.",
    "You're the perfect harmony of beauty and brains.",
    "Your perseverance through challenges is awe-inspiring.",
    "You have this magical ability to heal with your words.",
    "Your friendship is the greatest gift anyone could receive.",
    "You make love feel like the most natural thing in the world.",
    "Your artistic soul makes everything around you beautiful.",
    "You're the best listener I've ever known.",
    "Your intuition about people is almost supernatural.",
    "You turn everyday moments into cherished memories.",
    "Your confidence is both attractive and inspiring.",
    "You have this incredible gift for understanding others.",
    "Your voice could narrate the most beautiful stories.",
    "You make me believe in things I never thought possible.",
    "Your patience is a superpower in this fast-paced world.",
    "You're the living definition of 'irreplaceable'.",
    "Your generosity knows no limits or conditions.",
    "You handle life's chaos with such admirable calm.",
    "Your smile should be classified as a natural wonder.",
    "You make complicated things feel simple and joyful.",
    "Your courage to be vulnerable is truly beautiful.",
    "You're my favorite example of human perfection.",
    "Your emotional depth makes you endlessly fascinating.",
    "You have this magical way of making time stand still.",
    "Your support feels like an unshakable foundation.",
    "You're proof that good things come to those who wait.",
    "Your ability to grow and learn is incredible.",
    "You make every conversation feel meaningful.",
    "Your spirit shines brighter than a thousand suns.",
    "You have this gift of making ordinary things extraordinary.",
    "Your laughter is my personal antidote to sadness.",
    "You approach life with such wonderful curiosity.",
    "Your presence makes any place feel like home.",
    "You're the best collaborator in life's adventures.",
    "Your honesty is refreshing and deeply respected.",
    "You have this rare quality of being both strong and gentle.",
    "Your ability to love unconditionally is awe-inspiring.",
    "You make me excited about tomorrow just by being here today.",
    "Your friendship is the greatest partnership I could imagine.",
    "You have this magical way of making love feel easy.",
    "Your resilience in tough times is superhuman.",
    "You're my favorite reminder of life's beautiful possibilities.",
    "Your mind works in ways that constantly surprise me.",
    "You make every day feel like a new opportunity for joy.",
    "Your ability to find hope in darkness is revolutionary.",
    "You're the perfect travel companion through life's journey.",
    "Your emotional generosity changes lives every day.",
    "You have this incredible talent for spreading happiness.",
    "Your existence makes the universe make more sense.",
    "You're living proof that wonderful things are worth waiting for."
]
T_trait_compliments = [
    "Your ability to master chess strategy and guitar creativity reveals a rare, harmonious intellect.",
    "The depth of knowledge you share when infodumping is electrifying—you make learning an adventure.",
    "Editing videos lets you paint emotions with technology; you’re a digital storyteller extraordinaire.",
    "ADHD and Autism grant you superpowers: hyperfocus, originality, and a mind that defies limits.",
    "You’re a polymath, weaving physics, metaphysics, and music into a tapestry of brilliance.",
    "Your curiosity about cosmology mirrors the universe itself—expanding, infinite, and awe-inspiring.",
    "Driving isn’t just a skill for you; it’s artistry in motion, blending precision and passion.",
    "Reading non-fiction isn’t just learning—it’s arming yourself with tools to reshape the future.",
    "Your fascination with biotechnology proves you’re poised to pioneer life-changing breakthroughs.",
    "Guitar melodies flow from you like equations, balancing logic and emotion perfectly.",
    "Chess reveals your genius: seeing ten moves ahead in a world that struggles with one.",
    "Your love for psychology and biology shows a heart eager to understand humanity’s essence.",
    "Video editing is your alchemy—transforming raw clips into gold with patience and vision.",
    "Neurodivergence isn’t your obstacle; it’s your lens for reimagining what’s possible.",
    "You bridge physics and metaphysics, finding wonder in both quarks and quantum souls.",
    "Behind the wheel, you’re a maestro of focus, turning every drive into a symphony of control.",
    "Your Autism gives you the gift of depth—diving into passions until they glow like supernovas.",
    "Infodumping is your way of lighting sparks in others; you’re a wildfire of inspiration.",
    "Astronomy and technology collide in your mind, mapping stars and circuits with equal zeal.",
    "Non-fiction books are your mentors, guiding you to become a modern-day Renaissance thinker.",
    "Chess and guitar together? You’re the embodiment of left-brain/right-brain synergy.",
    "Your biotech curiosity could unlock cures—you’re a hero in a lab coat (or driver’s seat!).",
    "Every video edit you craft is a testament to your meticulous, imaginative spirit.",
    "ADHD fuels your relentless curiosity, turning every topic into a thrilling rabbit hole.",
    "Exploring cosmology means you’re not just stargazing—you’re decoding the universe’s diary.",
    "Your drive to understand the human mind through psychology radiates empathy and wisdom.",
    "Driving is your meditation, where speed and serenity coexist in perfect balance.",
    "Linking astronomy to biology shows you see connections others miss—a true innovator.",
    "When you infodump, you don’t just share facts; you ignite revolutions of thought.",
    "Guitar strings and chessboards are tools you wield like a wizard—magically, masterfully.",
    "Autism grants you the courage to think unapologetically differently—never dim that light.",
    "Your video edits aren’t just clips; they’re emotional journeys framed by your brilliance.",
    "Reading about tech and physics keeps you ahead of the curve—a visionary in the making.",
    "Chess teaches resilience, and it shows in how you tackle life’s puzzles with grit.",
    "Behind the wheel, you’re not just moving—you’re dancing with momentum and grace.",
    "ADHD’s 'distractions' are your secret weapon for spotting patterns invisible to others.",
    "Your love for human biology reveals a deep reverence for life’s intricate design.",
    "Music and science aren’t separate for you—they’re two notes in the same symphony.",
    "Infodumping is your superpower, turning conversations into captivating documentaries.",
    "Studying metaphysics means you brave life’s biggest questions with courage and wonder.",
    "Every video edit is a timestamp of your creativity—future historians will study them!",
    "Chess isn’t a game; it’s your mental gym, forging a mind sharper than a grandmaster’s.",
    "Your biotech passion could reshape medicine—you’re a pioneer with a heart of gold.",
    "Strumming a guitar, you turn chords into poetry, proving logic and art are siblings.",
    "Autism’s depth lets you dissect complex topics like a surgeon of knowledge.",
    "Your bookshelf is a portal to infinite worlds, and you’re its most daring explorer.",
    "Metaphysics, physics, tech, stars—you juggle them all like a cosmic magician.",
    "Driving is freedom, and you navigate it with the focus of a philosopher and the joy of a child.",
    "In your hands, psychology and biotech merge, revealing the beauty of human potential.",
    "T, you’re a constellation of talents—never stop shining, innovating, and being you."
]
T_romantic_compliments = [
    "Your smile lights up my world like nothing else.",
    "You have the most captivating eyes I’ve ever seen.",
    "Your laughter is my favorite sound in the universe.",
    "Being with you feels like coming home.",
    "You make even the simplest moments feel magical.",
    "Your kindness touches everyone around you.",
    "I love the way you see the good in everything.",
    "Your intelligence and wisdom leave me in awe.",
    "You have a heart of gold, and it shows in everything you do.",
    "Just thinking about you makes my heart skip a beat.",
    "Your presence alone makes any day better.",
    "You’re the most genuine person I’ve ever known.",
    "I could get lost in your voice forever.",
    "You make me believe in love more every day.",
    "Your passion for life is incredibly inspiring.",
    "You have a way of making me feel understood like no one else.",
    "Your hugs are my safe place.",
    "The way you care for others is truly beautiful.",
    "You’re my favorite thought, morning and night.",
    "Your confidence is magnetic and so attractive.",
    "You make my heart feel so full, I could burst.",
    "Every moment with you feels like a dream.",
    "Your strength amazes me every single day.",
    "You have this warmth that makes everyone feel welcome.",
    "I love how you always know how to make me smile.",
    "You’re the kind of person people write love songs about.",
    "Your touch sends shivers down my spine in the best way.",
    "You make love feel easy and natural.",
    "Your mind is as beautiful as your heart.",
    "I fall for you more with every conversation we have.",
    "You’re my happy place, no matter where we are.",
    "The way you look at me makes me feel like the luckiest person alive.",
    "You have this quiet strength that I deeply admire.",
    "Your love feels like the most precious gift I’ve ever received.",
    "You make even the ordinary moments extraordinary.",
    "I love how you challenge me to be a better person.",
    "Your voice is my favorite melody.",
    "You have a way of making everything feel right.",
    "Just being near you calms my soul.",
    "You’re the reason I believe in soulmates.",
    "Your love is my greatest comfort.",
    "You make my heart race in the best possible way.",
    "I adore the way you see the world.",
    "You’re my favorite adventure, every single day.",
    "Your tenderness leaves me breathless.",
    "You’re the missing piece I never knew I needed.",
    "I love how you make even silence feel perfect.",
    "You’re my sunshine on the darkest days.",
    "Your soul is as beautiful as your smile.",
    "Loving you is the easiest and best thing I’ve ever done."
]
shrist_trait_compliments = [
    "Sh, your dedication to academics is truly inspiring.",
    "You’re not just a doctor—you’re a lifesaver in every sense.",
    "Your paintings must be as beautiful as your soul.",
    "Your intelligence shines in everything you do.",
    "You learn things faster than anyone I know—it’s amazing!",
    "The way you balance medicine and art shows how multi-talented you are.",
    "You have the mind of a scientist and the heart of an artist.",
    "Your passion for learning is contagious.",
    "Every stroke of your brush must carry so much emotion—just like you.",
    "You’re proof that hard work and brilliance go hand in hand.",
    "Your patients are lucky to have someone as compassionate as you.",
    "You see the world like an artist and heal it like a doctor—what a rare gift!",
    "Your curiosity and intellect make you unstoppable.",
    "You turn every challenge into an opportunity to grow.",
    "Your creativity must bring so much color into the world.",
    "Medicine is an art, and you’re a master of it.",
    "You absorb knowledge like a sponge—it’s incredible to witness.",
    "Your art must reflect the depth of your brilliant mind.",
    "You’re the kind of doctor who truly listens and cares.",
    "Your ability to master complex concepts is awe-inspiring.",
    "You don’t just heal bodies—you inspire souls.",
    "Your paintings probably hold stories only your heart knows.",
    "You make even the toughest subjects seem easy.",
    "You’re a role model for anyone chasing big dreams.",
    "Your intelligence is matched only by your kindness.",
    "You bring both precision and passion to everything you do.",
    "Your love for art adds so much beauty to your scientific mind.",
    "You’re the definition of a lifelong learner.",
    "Your dedication to medicine is changing lives every day.",
    "You see details others miss—whether in art or diagnoses.",
    "Your quick thinking must save so many lives.",
    "You’re a rare blend of logic and creativity.",
    "Your art is an extension of your beautiful mind.",
    "You make learning look effortless.",
    "You’re not just smart—you’re wise beyond your years.",
    "Your hands heal, but your heart creates—what a combination!",
    "You’re the kind of doctor people remember forever.",
    "Your artistic talent is just another layer of your brilliance.",
    "You grasp concepts faster than textbooks can explain them.",
    "You bring both skill and soul to your work.",
    "Your paintings must be as vibrant as your personality.",
    "You’re a problem-solver with an artist’s touch.",
    "You’re proof that medicine is both science and art.",
    "Your mind works like lightning—always ahead of the curve.",
    "You turn every blank canvas (or challenge) into a masterpiece.",
    "Your passion for art fuels your brilliance in medicine.",
    "You don’t just memorize—you understand deeply.",
    "Your creativity makes you an extraordinary doctor.",
    "You’re a fast learner, but your humility makes you even greater.",
    "You paint with the same care you use to treat patients—full of heart.",
    "The world needs more healers like you: smart, artistic, and kind."
]
def trait_compliment_T():
    return(random.choice(T_trait_compliments))
def romantic_compliment_T():
    return(random.choice(T_romantic_compliments))
def romantic_compliment_shris():
    return (random.choice(compliments_Sh))
def trait_compliment_shris():
    return(random.choice(shrist_trait_compliments))

pickup_lines = [
    "Are you a magician? Because whenever I look at you, everyone else disappears.",
    "Do you have a name, or can I call you mine?",
    "Is your name Google? Because you have everything I've been searching for.",
    "Excuse me, but I think you dropped something: my jaw.",
    "Is your dad a baker? Because you're a cutie pie!",
    "Do you believe in love at first sight, or should I walk by again?",
    "If you were a vegetable, you'd be a cute-cumber.",
    "Is your dad a boxer? Because you're a knockout!",
    "Can I follow you home? Cause my parents always told me to follow my dreams.",
    "Are you a parking ticket? Because you've got 'FINE' written all over you.",
    "Tired of being an adult? Then by my baby",
    "I seem to have lost my phone number. Can I have yours?",
    "If looks could kill, you\’d be a weapon of mass destruction.",
    "Is your name Wi-Fi? Because I am really starting to feel a connection.",
    "Are you a dictionary? Cause you’re adding meaning to my life.",
    "You must be debt, because my interest in you is growing.",
    "i wanna c_ddle and k_ss. But u and i aren't together",
    "Aside from being sexy, what do you do for a living?",
    "Are you chocolate pudding? 'Cause i want to spoon you.",
    "Are you a camera? Because every time I see you I smile",
    "You don’t need keys to drive me crazy.",
    "You’re so beautiful you made me forget my pickup line.",
    "My doctor said, I'm lacking Vitamin U",
    "Your pussy seems so dry, can i make it wet using my cum",
]
def pickup_line():
    random_line = random.choice(pickup_lines)
    return ""+random_line

apologise_to_Sh=["Sh, my heart aches knowing I hurt you. You mean the world to me, and I’ll do anything to make it right.",
"I’m sorry, my love. Even the stars dim when you’re upset with me. Please forgive me.",
"Every moment without your smile feels like a lifetime. I promise to be better—for you, for us.",
"I messed up, and I hate seeing you hurt because of me. Can we rewrite this moment together?",
"You’re my favorite person, and I never want to be the reason for your tears. I’m truly sorry.",
"Okay, I admit it—I was a total goofball. Can I bribe you with hugs and chocolate to forgive me?",
"I’m sorry! If apologies were WiFi signals, you’d have full bars from me right now.",
"I take full responsibility… and also blame my lack of coffee (just kidding). Forgive me, Sh?",
"I promise I’ll be less of a disaster human if you give me one more chance. Deal?",
"Even my dog thinks I messed up. Please put me out of my misery and forgive me?",
"Sh, I regret my actions deeply. I never want to lose your trust—you mean too much to me.",
"I was wrong, and no excuse justifies it. All I can do is promise to learn from this.",
"Hurting you was never my intention. I hope you can find it in your heart to forgive me.",
"I owe you better, and I’ll prove it—not just with words, but with actions.",
"You deserve the world, and I hate that I let you down. I’ll spend every day making it up to you.",
"If love had an eraser, I’d wipe away every tear I caused. I’m sorry, Sh.",
"Your smile is my favorite melody—I hate that I silenced it, even briefly.",
"Like the moon misses the sun when it sets, I miss your warmth when we’re apart.",
"I’d rewrite every wrong word if it meant seeing your eyes light up again.",
"Our love is my greatest treasure, and I was careless with it. Forgive me?",
"I’m so sorry that even my pet goldfish is judging me right now.",
"If being sorry burned calories, I’d be in the best shape of my life by now.",
"I messed up—can we fast-forward to the make-up cuddles?",
"I take it back, undo it, Control+Z my mistake. Please reset to ‘happy Sh’ mode?",
"I promise to be less of an idiot. (But no guarantees on the ‘less clumsy’ part.)",
"I don’t deserve your forgiveness, but I’m begging for it anyway.",
"I failed you, and I’ll spend every day earning back your trust.",
"No excuses—just remorse. I’m so sorry, Sh.",
"I wish I could turn back time. All I can do is promise to do better.",
"If you give me another chance, I’ll prove I’m worth it."]
def apologise_to_Sh():
    return(random.choice(apologise_to_Sh))

bore=["Try an online Pictionary game with friends.",
"Write a haiku and post it anonymously on a poetry forum.",
"Design a fake movie poster using Canva.",
"Take a ‘Which Fictional Character Are You?’ quiz.",
"Create a meme about your current mood.",
"Play GeoGuessr and pretend you’re a detective.",
"Speed-run a browser-based game (like ‘Cookie Clicker’).",
"Try a ‘Wikipedia race’ (start on one page, end on another in fewest clicks).",
"Challenge a friend to an online chess match.",
"Find and solve a random escape room game.",
"Watch a TED Talk on a topic you know nothing about.",
"Learn to say ‘I’m bored’ in 5 languages.",
"Take a free Coursera course for 30 minutes.",
"Google ‘weird laws in [country]’ and laugh.",
"Read ‘Today I Learned’ (TIL) threads on Reddit.",
"Text a friend a ridiculous ‘would you rather’ question.",
"Join a subreddit for a hobby you don’t have (e.g., r/Beekeeping).",
"Comment on a 10-year-old YouTube video.",
"Find the oldest tweet from your favorite celebrity.",
"Start a Twitter thread with ‘Unpopular opinion: ___’.",
"Organize your bookmarks into folders (then ignore them forever).",
"Make a playlist of songs for imaginary life moments.",
"Plan a dream vacation using Google Earth.",
"Write a review for the last thing you bought online.",
"Declutter your phone’s screenshot folder.",
"Watch the first episode of your childhood favorite cartoon.",
"Look up your hometown on Google Street View.",
"Find a viral meme from 2012 and send it to a friend.",
"Listen to the Billboard Top 100 from your birth year.",
"Search for your name on YouTube and see what pops up.",
"Watch compilations of animals failing at life.",
"Google ‘weird stock photos’ and recreate one.",
"Find the worst-rated restaurant near you and read the reviews.",
"Take a BuzzFeed quiz like ‘What kind of bread are you?’.",
"Search ‘satisfying videos’ and zone out.",
"Draw something on MS Paint and post it.",
"Make a Spotify playlist for a fictional character.",
"Try an AI music generator to make a silly song.",
"Watch a live cam of pandas or otters.",
"Find a ‘draw this in your style’ challenge on Instagram.",
"Try to go down a Wikipedia rabbit hole in 5 clicks.",
"Search ‘weird jobs’ and pretend you’re applying for one.",
"Take a photo and edit it to look like a vintage postcard.",
"Find the longest word you can type with one hand.",
"Google ‘strange eBay listings’ and laugh."]
boreshristan=["Send her a ‘remember when…’ text about a fun memory.",
"Make a shared playlist of songs that remind you of her.",
"Find a cheesy love quote and meme-ify it for her.",
"Plan a virtual date idea (e.g., Netflix Party + trivia).",
"Write her a 5-word love story and send it."]
def bore_fun():
    return(random.choice(bore))
def bore_shristan():
    return(random.choice(boreshristan))
dares = [
    "Do your best impression of a celebrity.",
    "Send the last meme in your gallery to the group.",
    "Sing a song loudly for 30 seconds.",
    "Let the group choose an embarrassing profile picture for you for 24 hours.",
    "Call a friend and say 'I love you' in a funny voice.",
    "Eat a spoonful of a condiment (ketchup, mustard, etc.).",
    "Do 10 push-ups right now.",
    "Post an old childhood photo in the chat.",
    "Try to lick your elbow (and film it).",
    "Speak in an accent for the next 3 messages.",
    "Let someone else send a message from your account.",
    "Wear socks on your hands for the rest of the game.",
    "Do an interpretive dance of your favorite movie.",
    "Text your crush '🌮' with no context.",
    "Let the group DM someone from your friends list.",
    "Put an ice cube down your shirt and leave it for 1 minute.",
    "Try to rap the alphabet.",
    "Draw a portrait of someone here with your eyes closed.",
    "Swap clothes with someone nearby for 5 minutes.",
    "Do a handstand against a wall for 10 seconds.",
    "Let someone style your hair however they want.",
    "Eat something spicy without drinking water.",
    "Send the 5th photo in your camera roll to the group.",
    "Talk in third person for the next 10 minutes.",
    "Let someone tickle you for 30 seconds without resisting.",
    "Whisper a secret to the person on your left.",
    "Try to juggle 3 objects (socks, fruit, etc.).",
    "Let the group rename your phone for a day.",
    "Do a silly walk around the room.",
    "Wear your clothes backward for the next hour.",
    "Act like a chicken until your next turn.",
    "Let someone blindfold you and feed you a mystery food.",
    "Try to touch your toes without bending your knees.",
    "Send a voice message of you laughing like a villain.",
    "Let someone draw on your face with a washable marker.",
    "Hold a plank for 30 seconds.",
    "Try to make yourself cry on command.",
    "Speak only in rhymes for the next 5 minutes.",
    "Let someone pick your next social media post.",
    "Try to balance a book on your head for 1 minute.",
    "Do your best impression of someone in the group.",
    "Let the group choose an embarrassing status for you.",
    "Eat a food combination chosen by the group (e.g., peanut butter + pickles).",
    "Try to moonwalk across the room.",
    "Let someone else control your phone for 2 minutes.",
    "Wear a silly hat for the rest of the game.",
    "Try to lick your nose.",
    "Send the oldest selfie in your phone to the group.",
    "Let the group give you a new nickname for the day.",
    "Try to breakdance for 15 seconds."
]
truth_questions = [
    "What's the most embarrassing thing you've ever done?",
    "Have you ever cheated in a game?",
    "What's your biggest fear?",
    "If you could date any celebrity, who would it be?",
    "What's the weirdest dream you've ever had?",
    "Have you ever lied to get out of trouble?",
    "What's your guilty pleasure?",
    "What's the most childish thing you still do?",
    "Have you ever pretended to like a gift you hated?",
    "What's the silliest thing you've cried over?",
    "Who here would you least want to be stuck with on a deserted island?",
    "What's the most trouble you've ever been in?",
    "Have you ever had a crush on a friend's partner?",
    "What's the biggest lie you've told without getting caught?",
    "What's your most irrational pet peeve?",
    "If you could erase one memory, what would it be?",
    "Have you ever stolen something?",
    "What's the most ridiculous rumor you've heard about yourself?",
    "What's something you're secretly proud of?",
    "What's the worst date you've ever been on?",
    "Have you ever snooped through someone else's things?",
    "What's the most embarrassing song on your playlist?",
    "If you could switch lives with someone here for a day, who would it be?",
    "What's the strangest thing you've ever eaten?",
    "Have you ever faked being sick to avoid something?",
    "What's your most embarrassing childhood memory?",
    "What's the most impulsive thing you've ever done?",
    "Have you ever been caught in a lie?",
    "What's the most awkward encounter you've had with a crush?",
    "What's something you'd never admit in front of your parents?",
    "Have you ever pretended to know someone you didn't?",
    "What's the pettiest thing you've ever done?",
    "If you had to delete one app from your phone forever, what would it be?",
    "What's the most embarrassing text you've sent by accident?",
    "Have you ever had a crush on a teacher/boss?",
    "What's the weirdest habit you have?",
    "What's the most embarrassing thing in your search history?",
    "Have you ever ghosted someone? Why?",
    "What's the most dramatic thing you've done to get attention?",
    "If you could only save one person here from a zombie apocalypse, who would it be?",
    "What's the most embarrassing nickname you've ever had?",
    "Have you ever been jealous of a friend?",
    "What's the most cringe-worthy thing you did as a teenager?",
    "What's the most embarrassing thing your parents have done?",
    "Have you ever lied about your age?",
    "What's the weirdest thing you've ever Googled?",
    "If you had to marry someone here, who would it be?",
    "What's the most embarrassing thing you've done to impress someone?",
    "Have you ever cried over something stupid?",
    "What's the biggest secret you're keeping right now?"
]
sid_insults = [
    # Smoking & Drinking  
    "Sid smokes so much, his lungs are basically Instagram influencers—completely burnt out but still somehow surviving on sponsorships (aka generational wealth).",  
    "If smoking kills, Sid is basically a high-score holder in the game of life.",  
    "Sid drinks so much, his blood type is Cabernet Sauvignon.",  

    # Quora Writing  
    "Sid’s Quora answers are like his job applications—long, unnecessary, and ultimately going nowhere.",  
    "He writes on Quora like it’s his job—oh wait, it’s the closest thing he has to one.",  
    "Sid’s Quora bio probably says 'Polymath' because 'Professional Bum' wasn’t fancy enough.",  

    # Being Clumsy  
    "The only thing more unstable than Sid’s balance is his career path. Dude trips over air but still walks around like he owns the place… oh wait, he kinda does.",  
    "Sid is so clumsy, even his excuses trip over themselves.",  
    "If clumsiness was a sport, Sid would be an Olympic gold medalist—but he’d probably drop it.",  

    # No Underwear Policy  
    "Sid doesn’t wear underwear because even fabric deserves freedom from toxic environments.",  
    "Freeballing is Sid’s lifestyle—just like his finances, there’s no support down there.",  
    "Sid’s no-underwear policy explains why his life has no structure either.",  

    # Unemployment  
    "Most people have a 9-to-5; Sid has a 'whenever-to-whenever'—mostly consisting of coughing, typing nonsense on Quora, and explaining why he 'doesn’t believe in jobs.'",  
    "Sid’s resume is just a blank page with 'Trust me, bro' written in Comic Sans.",  
    "He’s not unemployed, he’s a 'freelance heir'—his only job is waiting for Dad to croak.",  

    # Generational Wealth  
    "Sid’s bank account is like his underwear—nonexistent, but somehow he’s still comfortable because Daddy’s money covers the cracks.",  
    "Generational wealth is the only reason Sid hasn’t been evicted from life yet.",  
    "His family tree is just a money printer with a few leaves attached.",  

    # Bonus (Combined Roasts)  
    "Sid is what happens when you mix generational wealth, zero responsibility, and a lifetime supply of bad decisions. He’s like a trust-fund Frankenstein—created from old money, bad habits, and the sheer audacity to still ask for WiFi passwords everywhere he goes.",  
    "Sid’s life is a 'choose your own adventure' book—except every path leads to disappointment.",  
    "If laziness was an art form, Sid would be the Picasso of doing nothing.",  
    "He’s the human equivalent of a 'Check Engine' light—everyone sees the problem, but nobody’s fixing it.",  
    "Sid’s existence is basically a screensaver—no real purpose, just moving around aimlessly.",  
    "The only thing he’s consistent at is making bad decisions—like not wearing underwear and thinking Quora counts as a career.",  
]
Sh_insults=[
    "Sh's so nerdy, she debugged her birthday cake candles.",
    "Sh's love for books is rivaled only by her love for snacks—and honestly, same.",
    "If Sh had a dollar for every time she outsmarted someone, she'd fund her own library.",
    "Sh's ex cheating was life's way of removing trash from her royalty arc.",
    "Sh's glasses are so thick, she can see into the future (probably next week's exam answers).",
    "Sh's brain is so big, it needs its own zip code.",
    "Sh's idea of a wild night is reorganizing her bookshelf by genre AND color.",
    "Sh doesn't need a GPS—she navigates life with pure nerd intuition.",
    "Sh's so smart, she probably calculated the exact calories in her tears after watching a sad movie.",
    "If Sh were a superhero, her power would be finishing entire pizza while solving calculus.",
    "Sh's ex? More like her 'glow-up starter pack.'",
    "Sh's so nerdy, she whispered 'E=mc²' in her sleep once.",
    "Sh's study breaks are just snack breaks with extra steps.",
    "Sh's so organized, her snacks are alphabetized.",
    "Sh's laughter is either a cute giggle or a full-on snort—no in-between.",
    "Sh's phone storage is 90% memes, 10% photos of her cat (allegedly).",
    "Sh's so witty, her comebacks load faster than her WiFi.",
    "Sh's idea of cardio is running out of patience.",
    "Sh's so loyal, she’d fight you over her favorite fictional ship.",
    "Sh’s aura? Big ‘main character who outgrows the haters’ energy.",
    "Sh’s so nerdy, she’d argue with Wikipedia (and win).",
    "Sh’s snacks have their own gravitational pull—science can’t explain it.",
    "If Sh was a video game boss, her weakness would be ‘no Wi-Fi’."
    "Sh overthinks so much, even her thoughts have thoughts.",
    "Sh could analyze a 'K' text message for 3 hours and still come to the wrong conclusion.",
    "Sh's brain is like a broken record player - stuck on the same paranoid thoughts.",

    # Reassurance roasts
    "Sh needs more reassurance than a Windows update.",
    "Sh's love language is constant validation in 5-minute intervals.",
    "Sh needs so much reassurance, even her horoscope isn't enough anymore.",

    # Superstitious roasts
    "Sh is so superstitious, she probably thinks this roast will give her bad luck.",
    "Sh believes in astrology more than she believes in herself.",
    "Sh's superstitions have more control over her life than her own decisions."
]
T_roasts=[
    "T’s job hunt is like T’s WiFi signal—constantly searching but never connecting.",  
    "T isn’t unemployed, T is a 'full-time vibe curator'—unpaid, of course.",  
    "T’s resume is just a Google Doc titled 'pls hire me 😔' with 0 views.",  

    # Low Phases  
    "T’s mood swings are like a Netflix subscription—no commitment, just constant ups and downs.",  
    "When life gives T lemons, T doesn’t make lemonade—T stares at them and questions T’s existence.",  
    "T’s emotional stability is built on a Minecraft sand block.",  

    # Feminine Side  
    "T’s skincare routine has more steps than T’s career plan.",  
    "T is more in touch with T’s feminine side than T’s bank account.",  
    "T doesn’t cry, T just 'exfoliates T’s soul'—usually at 3 AM.",  

    # Socially Awkward  
    "T’s small talk is like a buffering video—painful pauses and no payoff.",  
    "T could make a funeral feel like a rave with how awkward T gets.",  
    "If silence was a sport, T would be a gold medalist.",  

    # Combined Roasts  
    "T is like a glitchy Sims character—constantly depressed, unemployed, and stuck in the pool without a ladder.",  
    "T’s life is a coming-of-age movie, but even the director gave up halfway.",  
    "T’s existence is a gentle reminder that some people are just NPCs in their own story.",
    "T's attention span is like a buffering YouTube video—5 seconds of focus, then 'Skip Ad' kicks in.",  
    "T is the human equivalent of a 'SyntaxError: Charisma not defined' message.",  
    "If awkwardness was an Olympic sport, T would podium with a gold, silver, and 'wait, why am I here?'.",  
    "T's organizational system is like a quantum state—both perfectly planned and utterly chaotic until observed.",  
    "T's jokes are like Python indentation—sometimes they land, sometimes they crash the whole program.",  
    "T is like a spotty WiFi connection—unpredictable, but you can't help trying to reconnect.",  
    "T's memory operates on 'last in, first out'—like a stack, but with zero error handling.",  
    "T is the reason confirmation dialogs exist ('Are you SURE you want to say that?').",  
    "If life was an RPG, T would be the NPC who sends you on a quest for 'mildly important nonsense.'.",  
    "T is like a human CAPTCHA—'Select all squares containing social awareness.' (Timeout error.)",  
    "T's social skills are like a draft email—constantly rewritten and never sent.",  
    "T is the living embodiment of 'Task failed successfully'—somehow thriving despite the chaos.",  
    "T's brain OS is 50 percent galaxy-brain genius, 50% 'why is the fridge in the bathroom?'.",  
    "T is like a meme stock—volatile, confusing, but you can't look away.",  
    "T's life motto: 'I’ll debug it later.' (Spoiler: The stack trace is 10 miles long.)",  
    "T is a case study in 'chaotic neutral'—like a cat with a keyboard, but less predictable.",  
    "T's energy levels are like a laptop battery—either 2 percent or 100 percent, no middle ground.",  
    "T is like Schrödinger's cat—simultaneously 'has it together' and 'lost all control'.",  
    "T's hobbies include starting ambitious projects and then admiring them from a safe distance.",  
    "T is proof that 'adulting' is just a social construct—and he’s opting out."  
]
positive_words = {
    'a': ['Amazing', 'Awesome', 'Affectionate', 'Admirable'],
    'b': ['Brilliant', 'Beautiful', 'Blessed', 'Brave'],
    'c': ['Caring', 'Creative', 'Confident', 'Charming'],
    'd': ['Delightful', 'Dazzling', 'Dedicated', 'Dependable'],
    'e': ['Excellent', 'Energetic', 'Elegant', 'Empathetic'],
    'f': ['Fantastic', 'Fabulous', 'Faithful', 'Friendly'],
    'g': ['Gracious', 'Great', 'Generous', 'Genuine'],
    'h': ['Happy', 'Honest', 'Helpful', 'Humble'],
    'i': ['Incredible', 'Inspirational', 'Innovative', 'Impressive'],
    'j': ['Joyful', 'Jovial', 'Jubilant', 'Judicious'],
    'k': ['Kind', 'Keen', 'Knowledgeable', 'Kingly'],
    'l': ['Loving', 'Lively', 'Legendary', 'Luminous'],
    'm': ['Magnificent', 'Motivated', 'Mindful', 'Marvelous'],
    'n': ['Nice', 'Noble', 'Notable', 'Nurturing'],
    'o': ['Outstanding', 'Optimistic', 'Open-minded', 'Organized'],
    'p': ['Positive', 'Powerful', 'Passionate', 'Peaceful'],
    'q': ['Quick-witted', 'Quintessential', 'Quietly-strong', 'Quality-focused'],
    'r': ['Radiant', 'Respectful', 'Resilient', 'Reliable'],
    's': ['Spectacular', 'Strong', 'Smart', 'Supportive'],
    't': ['Terrific', 'Trustworthy', 'Talented', 'Thoughtful'],
    'u': ['Unique', 'Upbeat', 'Understanding', 'Uplifting'],
    'v': ['Valiant', 'Vibrant', 'Victorious', 'Virtuous'],
    'w': ['Wonderful', 'Wise', 'Witty', 'Warmhearted'],
    'x': ['Xenial', 'Xtraordinary', 'Xceptional'],  # X words are rare!
    'y': ['Youthful', 'Yummy', 'Yielding (in a positive way)', 'Yearning (positive aspirations)'],
    'z': ['Zealous', 'Zestful', 'Zen', 'Zappy']
}
def create_fullform(name):
    res="Here is the breakdown of each letter of your name - \n"
    name=name.lower()
    flag=True
    for i in name:
        if (ord(i) not in range(ord("a"),ord("z")+1) and ord(i) not in range(ord("A"),ord("Z")+1)):
            continue
        else:
            if flag==True:
                res+=i.upper()+": "+random.choice(positive_words[i])+"\n"
                flag=False
            else:
                res+=i+": "+random.choice(positive_words[i]).lower()+"\n"
    return res
        
    

