#File containing suggestions to cure boredom, truth questions and dares.
import random
dares = [
    "Do your best impression of a celebrity.",
    "Send the last meme in your gallery to the group.",
    "Sing a song loudly for 30 seconds.",
    "Let the group choose an embarrassing profile picture for you for 24 hours.",
    "Call a friend and say 'I love you' in a funny voice.",
    "Eat a spoonful of a condiment (ketchup, mustard, etc.).",
    "Do 10 push-ups right now.",
    "Post an old childhood photo in the chat.",
    "Try to lick your elbow (and film it).",
    "Speak in an accent for the next 3 messages.",
    "Let someone else send a message from your account.",
    "Wear socks on your hands for the rest of the game.",
    "Do an interpretive dance of your favorite movie.",
    "Text your crush '🌮' with no context.",
    "Let the group DM someone from your friends list.",
    "Put an ice cube down your shirt and leave it for 1 minute.",
    "Try to rap the alphabet.",
    "Draw a portrait of someone here with your eyes closed.",
    "Swap clothes with someone nearby for 5 minutes.",
    "Do a handstand against a wall for 10 seconds.",
    "Let someone style your hair however they want.",
    "Eat something spicy without drinking water.",
    "Send the 5th photo in your camera roll to the group.",
    "Talk in third person for the next 10 minutes.",
    "Let someone tickle you for 30 seconds without resisting.",
    "Whisper a secret to the person on your left.",
    "Try to juggle 3 objects (socks, fruit, etc.).",
    "Let the group rename your phone for a day.",
    "Do a silly walk around the room.",
    "Wear your clothes backward for the next hour.",
    "Act like a chicken until your next turn.",
    "Let someone blindfold you and feed you a mystery food.",
    "Try to touch your toes without bending your knees.",
    "Send a voice message of you laughing like a villain.",
    "Let someone draw on your face with a washable marker.",
    "Hold a plank for 30 seconds.",
    "Try to make yourself cry on command.",
    "Speak only in rhymes for the next 5 minutes.",
    "Let someone pick your next social media post.",
    "Try to balance a book on your head for 1 minute.",
    "Do your best impression of someone in the group.",
    "Let the group choose an embarrassing status for you.",
    "Eat a food combination chosen by the group (e.g., peanut butter + pickles).",
    "Try to moonwalk across the room.",
    "Let someone else control your phone for 2 minutes.",
    "Wear a silly hat for the rest of the game.",
    "Try to lick your nose.",
    "Send the oldest selfie in your phone to the group.",
    "Let the group give you a new nickname for the day.",
    "Try to breakdance for 15 seconds."
]
truth_questions = [
    "What's the most embarrassing thing you've ever done?",
    "Have you ever cheated in a game?",
    "What's your biggest fear?",
    "If you could date any celebrity, who would it be?",
    "What's the weirdest dream you've ever had?",
    "Have you ever lied to get out of trouble?",
    "What's your guilty pleasure?",
    "What's the most childish thing you still do?",
    "Have you ever pretended to like a gift you hated?",
    "What's the silliest thing you've cried over?",
    "Who here would you least want to be stuck with on a deserted island?",
    "What's the most trouble you've ever been in?",
    "Have you ever had a crush on a friend's partner?",
    "What's the biggest lie you've told without getting caught?",
    "What's your most irrational pet peeve?",
    "If you could erase one memory, what would it be?",
    "Have you ever stolen something?",
    "What's the most ridiculous rumor you've heard about yourself?",
    "What's something you're secretly proud of?",
    "What's the worst date you've ever been on?",
    "Have you ever snooped through someone else's things?",
    "What's the most embarrassing song on your playlist?",
    "If you could switch lives with someone here for a day, who would it be?",
    "What's the strangest thing you've ever eaten?",
    "Have you ever faked being sick to avoid something?",
    "What's your most embarrassing childhood memory?",
    "What's the most impulsive thing you've ever done?",
    "Have you ever been caught in a lie?",
    "What's the most awkward encounter you've had with a crush?",
    "What's something you'd never admit in front of your parents?",
    "Have you ever pretended to know someone you didn't?",
    "What's the pettiest thing you've ever done?",
    "If you had to delete one app from your phone forever, what would it be?",
    "What's the most embarrassing text you've sent by accident?",
    "Have you ever had a crush on a teacher/boss?",
    "What's the weirdest habit you have?",
    "What's the most embarrassing thing in your search history?",
    "Have you ever ghosted someone? Why?",
    "What's the most dramatic thing you've done to get attention?",
    "If you could only save one person here from a zombie apocalypse, who would it be?",
    "What's the most embarrassing nickname you've ever had?",
    "Have you ever been jealous of a friend?",
    "What's the most cringe-worthy thing you did as a teenager?",
    "What's the most embarrassing thing your parents have done?",
    "Have you ever lied about your age?",
    "What's the weirdest thing you've ever Googled?",
    "If you had to marry someone here, who would it be?",
    "What's the most embarrassing thing you've done to impress someone?",
    "Have you ever cried over something stupid?",
    "What's the biggest secret you're keeping right now?"
]
bore=["Try an online Pictionary game with friends.",
"Write a haiku and post it anonymously on a poetry forum.",
"Design a fake movie poster using Canva.",
"Take a ‘Which Fictional Character Are You?’ quiz.",
"Create a meme about your current mood.",
"Play GeoGuessr and pretend you’re a detective.",
"Speed-run a browser-based game (like ‘Cookie Clicker’).",
"Try a ‘Wikipedia race’ (start on one page, end on another in fewest clicks).",
"Challenge a friend to an online chess match.",
"Find and solve a random escape room game.",
"Watch a TED Talk on a topic you know nothing about.",
"Learn to say ‘I’m bored’ in 5 languages.",
"Take a free Coursera course for 30 minutes.",
"Google ‘weird laws in [country]’ and laugh.",
"Read ‘Today I Learned’ (TIL) threads on Reddit.",
"Text a friend a ridiculous ‘would you rather’ question.",
"Join a subreddit for a hobby you don’t have (e.g., r/Beekeeping).",
"Comment on a 10-year-old YouTube video.",
"Find the oldest tweet from your favorite celebrity.",
"Start a Twitter thread with ‘Unpopular opinion: ___’.",
"Organize your bookmarks into folders (then ignore them forever).",
"Make a playlist of songs for imaginary life moments.",
"Plan a dream vacation using Google Earth.",
"Write a review for the last thing you bought online.",
"Declutter your phone’s screenshot folder.",
"Watch the first episode of your childhood favorite cartoon.",
"Look up your hometown on Google Street View.",
"Find a viral meme from 2012 and send it to a friend.",
"Listen to the Billboard Top 100 from your birth year.",
"Search for your name on YouTube and see what pops up.",
"Watch compilations of animals failing at life.",
"Google ‘weird stock photos’ and recreate one.",
"Find the worst-rated restaurant near you and read the reviews.",
"Take a BuzzFeed quiz like ‘What kind of bread are you?’.",
"Search ‘satisfying videos’ and zone out.",
"Draw something on MS Paint and post it.",
"Make a Spotify playlist for a fictional character.",
"Try an AI music generator to make a silly song.",
"Watch a live cam of pandas or otters.",
"Find a ‘draw this in your style’ challenge on Instagram.",
"Try to go down a Wikipedia rabbit hole in 5 clicks.",
"Search ‘weird jobs’ and pretend you’re applying for one.",
"Take a photo and edit it to look like a vintage postcard.",
"Find the longest word you can type with one hand.",
"Google ‘strange eBay listings’ and laugh."]
borerom=["Send her a ‘remember when…’ text about a fun memory.",
"Make a shared playlist of songs that remind you of her.",
"Find a cheesy love quote and meme-ify it for her.",
"Plan a virtual date idea (e.g., Netflix Party + trivia).",
"Write her a 5-word love story and send it."]
def bore_fun():
    return(random.choice(bore))
def bore_shristan():
    return(random.choice(boreshristan))
def get_truth():
    return(random.choice(truth_questions))
def get_dare():
    return(random.choice(dares))
